# Generated by Django 3.2.7 on 2021-10-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='used',
        ),
    ]
