# Generated by Django 3.2.7 on 2021-10-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_reward_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
