# Generated by Django 3.2.7 on 2021-11-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_reward_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
