# Generated by Django 3.2.7 on 2021-10-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
