# Generated by Django 3.2.7 on 2021-09-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210918_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='type',
        ),
    ]
