# Generated by Django 3.2.7 on 2021-09-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_coffee_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='friendly_price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
