# Generated by Django 3.2.7 on 2021-09-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_price_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='product',
        ),
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
