# Generated by Django 3.2.7 on 2021-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description_full',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='free_delivery_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
