# Generated by Django 3.2.7 on 2021-09-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210921_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_multiple',
            field=models.IntegerField(default=False),
        ),
    ]
