# Generated by Django 3.2.7 on 2021-09-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_offer_product_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='display_in_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
