# Generated by Django 3.2.7 on 2021-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210921_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='banner_delimiter',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='description_full_delimiter',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
