# Generated by Django 3.2.7 on 2021-09-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_description_full_delimiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='banner_delimiter',
        ),
    ]
