# Generated by Django 3.2.7 on 2021-09-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_offer_banner_delimiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
