# Generated by Django 3.2.7 on 2021-09-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20210924_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='description',
        ),
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='size_description',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='category',
            name='type_description',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
