# Generated by Django 3.2.7 on 2021-09-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210924_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='information',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='type',
            name='information',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
