# Generated by Django 3.2.7 on 2021-09-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20210924_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='information',
        ),
        migrations.RemoveField(
            model_name='type',
            name='information',
        ),
        migrations.AddField(
            model_name='category',
            name='size_information',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='category',
            name='type_information',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='category',
            name='size_description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
