# Generated by Django 3.2.7 on 2021-09-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20210924_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type_information_delimiter',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
