# Generated by Django 3.2.7 on 2021-09-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_category_size_information_delimiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_full_delimiter',
            new_name='description_delimiter',
        ),
    ]
