# Generated by Django 3.2.7 on 2021-09-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_rename_description_full_delimiter_product_description_delimiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='size_information_delimiter',
            new_name='information_delimiter',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_information_delimiter',
        ),
    ]
