# Generated by Django 3.2.7 on 2021-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20210930_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='delivery_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
