# Generated by Django 3.2.7 on 2021-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=6),
            preserve_default=False,
        ),
    ]
