# Generated by Django 3.2.7 on 2021-10-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_delimiter',
            field=models.CharField(default=';', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=models.TextField(default='Full Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_price',
            field=models.CharField(default='£7.50 - 250g', max_length=100),
        ),
    ]
