# Generated by Django 3.2.7 on 2021-10-26 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0040_auto_20211026_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
