# Generated by Django 3.2.7 on 2021-10-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_remove_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=models.TextField(),
        ),
    ]
