# Generated by Django 3.2.7 on 2021-11-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_auto_20211026_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
